var express = require('express');
var app = express();
var server = require('http').createServer(app);

var io = require('socket.io')(server);
var port = 3030;

server.listen(port, function() {
  console.log('Port Connected', port);
});

app.use(express.static(__dirname + '/public'));

io.on('Connected', function(socket) {
  console.log('Initiated');
  socket.on('New Message', function(data) {
    console.log('Data Received', data.message);
    socket.broadcast.emit('New Message', {
      username: data.username,
      message: data.message,
    });
  });
});

var randwords = [
'Atlas',
'Venus',
'Arousal',
'Asian',
'Ball',
'Basketball',
'Mustard',
'Pitch',
'Tar',
'Blood',
'Job',
'Blower',
'Bullock',
'pollok',
'sooner',
'bob',
'begger',
'bun',
'butter',
'plug',
'toris',
'sock',
'racoon',
'rap',
'aunt',
'dam',
'sick',
'dil',
'skype',
'flag',
'freckle',
'fate',
'ford',
'fling',
'frock',
'flap',
'lion',
'tiger',
'orange',
'apple',
'timer',
'watch',
'home',
'jet',
'engine',
'highway',
'ubuntu',
'linux',
'server',
'colorado',
'vulcun',
'mouse',
'bottle',
'god',
'plastic',
'charger',
'table',
'Anal',
'Anus',
'Arse',
'Ass',
'Ballsack',
'Balls',
'Bastard',
'Bitch',
'Biatch',
'Bloody',
'Blowjob',
'Blow',
'Bollock',
'Bollok',
'Boner',
'Boob',
'Bugger',
'Bum',
'Butt',
'Buttplug',
'Clitoris',
'Cock',
'Coon',
'Crap',
'Cunt',
'Damn',
'Dick',
'Dildo',
'Dyke',
'Fag',
'Feck',
'Fellate',
'Fellatio',
'Felching',
'Fuck',
'Fcuk',
'Jerk',
'Jizz',
'Knobend',
'Knocked',
'Labia',
'Lmao',
'Lmfao',
'Muff',
'Omg',
'Penis',
'Piss',
'Poop',
'Prick',
'Pube',
'Pussy',
'Queer',
'Scrotum',
'Sex',
'Shit',
'Shitty',
'Sh1t',
'Slut',
'Smegma',
'Spunk',
'Tit',
'Tosser',
'Turd',
'Twat',
'Vagina',
'Wank',
'iron',
'fan',
'oil',
'queen',
'king',
'secular',
'religious',
'religion',
'shop',
'shopping',
'xbox',
'playstation',
'play',
'dell',
'curd',
'toss',
'pizza',
'cheese',
'milk',
'eggs',
'Driver', 
'toyota',
'potter', 
'Harry', 
'Luxury',
'Smart',
'Colgate', 
'facebook',
'orkut',
'gmail',
'yahoo',
'Mars', 
'Earth', 
'Tyrion',
'Japan',
'Dell',
'Apple',
'Virginia',
'Louisiana',
'Kurt',
'Gravy',
'Lap',
'Jackal',
];

var blocked = {
  'ANAL' : true, 
  'ANUS' : true, 
  'ARSE' : true, 
  'ASS' : true, 
  'BALLSACK' : true, 
  'BALLS' : true, 
  'BASTARD' : true, 
  'BITCH' : true, 
  'BIATCH' : true, 
  'BLOODY' : true, 
  'BLOWJOB' : true, 
  'BLOW' : true, 
  'BOLLOCK' : true, 
  'BOLLOK' : true, 
  'BONER' : true, 
  'BOOB' : true, 
  'BUGGER' : true, 
  'BUM' : true, 
  'BUTT' : true, 
  'BUTTPLUG' : true, 
  'CLITORIS' : true, 
  'COCK' : true, 
  'COON' : true, 
  'CRAP' : true, 
  'CUNT' : true, 
  'DAMN' : true,
  'DICK' : true, 
  'DILDO' : true, 
  'DYKE' : true, 
  'FAG' : true, 
  'FECK' : true, 
  'FELLATE' : true, 
  'FELLATIO' : true, 
  'FELCHING' : true, 
  'FUCK' : true, 
  'FCUK' : true, 
  'FUDGEPACKER': true, 
  'FUDGE' : true, 
  'FLANGE' : true, 
  'GODDAMN' : true, 
  'DAMMIT': true, 
  'HELL': true, 
  'HOMO': true, 
  'JERK': true, 
  'JIZZ': true, 
  'KNOBEND': true,
  'KNOCKED' : true, 
  'LABIA': true, 
  'LMAO' : true, 
  'LMFAO': true, 
  'MUFF' : true, 
  'OMG' : true, 
  'PENIS': true, 
  'PISS': true, 
  'POOP': true, 
  'PRICK' : true, 
  'PUBE': true, 
  'PUSSY': true, 
  'QUEER': true, 
  'SCROTUM': true, 
  'SEX': true, 
  'SHIT': true, 
  'SHITTY': true, 
  'SH1T' : true, 
  'SLUT' : true, 
  'SMEGMA' : true, 
  'SPUNK' : true, 
  'TIT': true, 
  'TOSSER': true, 
  'TURD' : true, 
  'TWAT' : true, 
  'VAGINA' : true, 
  'WANK' : true, 
  'WHORE' : true, 
  'WTF' : true, 
  'DAMON' : true, 
  'TERRA' : true, 
  'WYRDEN' : true, 
  'ASTERIA' : true, 
  'LAVEY' : true, 
  'SMASH' : true, 
  'TOOTHLESS' : true, 
  'NIGHTSHADE' : true, 
  'GRIM' : true, 
  'VITRIS' : true, 
  'SHADOWBOLT' : true, 
  'NEPTUNE' : true, 
  'ARYA' : true, 
  'CRUSHBUG' : true, 
  'MIDORI' : true, 
  'ZEENA' : true, 
  'WILLOW' : true, 
  'VIRIDA' : true, 
  'LOSNA' : true, 
  'KURISO' : true, 
  'GRAVEYARD' : true,
  'LAPIS': true,
  'JACKS' : true,
};

var randMsgGen = function() {
  var length = Math.floor(Math.random() * 7) + 1;
  var message = "";
  var username = "";

  for (var i = 0; i < length; ++i) {
    var wordNum = Math.floor(Math.random() * randwords.length);
    message += randwords[wordNum] + " ";
  }

  return {
    username : randwords[Math.floor(Math.random() * 50) + 1],
    message: message,
  };
};

var blockMsg = function(data) {
  var wordArray = data.message.split(" ");
  for (var i = 0; i < wordArray.length; i++) {
    if (blocked[wordArray[i].toUpperCase()]) {
      wordArray[i] = "xxxx";
    }
  }

  return {
    username: data.username,
    message: wordArray.join(" "),
  }
};

var messenger = function() {
  io.sockets.emit('new message' , blockMsg(randMsgGen()));
  setTimeout(messenger, 5);
};

messenger();
